name: Build wheels

#on: release
on: push

jobs:
  build_wheels:
    name: Build wheels on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    timeout-minutes: 20
    env:
      CIBW_SKIP: "cp27-* pp27-*"
      CIBW_BEFORE_BUILD: "pip install cython"
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.8"
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.10.0 cython
      - name: Build wheels
        run: |
          make build-vendored-deps
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
